const initialState = {
  ads: [
    {
      id: '1',
      title: 'Fusce hendrerit ornare',
      content: 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin sit amet ex et lectus vulputate facilisis sed non neque.',
      publicationDate: '13.02.2022',
      updateDate: '16.03.2022',
      email: 'user1@gmail.com',
      status: 'draft',
      phone: '111 222 333',
      location: 'Cracow',
    },
    {
      id: '2',
      title: 'Ipsum sed ultricies',
      content: 'Nam nisl risus, tristique nec odio vel, pellentesque maximus metus. Nam a purus nec lorem lacinia molestie.',
      publicationDate: '17.02.2022',
      updateDate: '17.02.2022',
      email: 'user2@gmail.com',
      status: 'publihed',
      images: '/images/adsImages/car01.jpg',
      prise: 12400,
      phone: '123 321 444',
      location: 'Warsaw',
    },
    {
      id: '3',
      title: 'Fusce non dictum eros',
      content: 'Sed pharetra quam id maximus rhoncus. Morbi at nisi a magna bibendum laoreet eu eget magna. Sed euismod nec tellus eget ultricies. Integer blandit feugiat ligula vitae ultrices.',
      publicationDate: '03.04.2022',
      updateDate: '18.04.2022',
      email: 'user3@gmail.com',
      status: 'closed',
      images: '/images/adsImages/iphone.jpg',
      prise: 850,
      phone: '876 888 432',
      location: 'Warsaw',
    },
    {
      id: '4',
      title: 'Sed elementum fringilla',
      content: 'Sed vestibulum arcu quis magna convallis, sit amet tempor sem tempor. Cras fringilla, lectus sed accumsan imperdiet, diam dui consectetur lectus, id mattis mauris ligula pulvinar libero.',
      publicationDate: '21.05.2022',
      updateDate: '21.05.2022',
      email: 'user@gmail.com',
      status: 'draft',
      images: '/images/adsImages/bike01.jpg',
      prise: 990,
      phone: '321 321 333',
      location: 'Cracow',
    },
    {
      id: '5',
      title: 'Interdum et malesuada',
      content: 'Pellentesque a molestie nisi. Aenean fermentum justo in elit sodales feugiat. Maecenas egestas ex quis dignissim rhoncus. Mauris ac varius nibh, ut suscipit lorem. Donec eu ante ligula. Suspendisse non quam sed metus blandit fringilla vitae eget urna. Suspendisse molestie eu ante a pharetra.',
      publicationDate: '19.03.2022',
      updateDate: '25.03.2022',
      email: 'user@gmail.com',
      status: 'published',
    },
    {
      id: '6',
      title: 'Sed elementum fringilla lacinia',
      content: 'Sed vestibulum arcu quis magna convallis, sit amet tempor sem tempor. Cras fringilla, lectus sed accumsan imperdiet, diam dui consectetur lectus, id mattis mauris ligula pulvinar libero.',
      publicationDate: '21.05.2022',
      updateDate: '21.05.2022',
      email: 'user@gmail.com',
      status: 'draft',
      images: '/images/adsImages/camera.jpg',
      prise: 1200,
      phone: '321 321 333',
      location: 'Cracow',
    },
    {
      id: '7',
      title: 'Interdum et malesuada',
      content: 'Pellentesque a molestie nisi. Aenean fermentum justo in elit sodales feugiat. Maecenas egestas ex quis dignissim rhoncus. Mauris ac varius nibh, ut suscipit lorem. Donec eu ante ligula. Suspendisse non quam sed metus blandit fringilla vitae eget urna. Suspendisse molestie eu ante a pharetra.',
      publicationDate: '19.03.2022',
      updateDate: '25.03.2022',
      email: 'user@gmail.com',
      status: 'published',
    },
    {
      id: '8',
      title: 'Fusce hendrerit ornare',
      content: 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin sit amet ex et lectus vulputate facilisis sed non neque.',
      publicationDate: '13.02.2022',
      updateDate: '16.03.2022',
      email: 'user1@gmail.com',
      status: 'draft',
      phone: '111 222 333',
      location: 'Cracow',
    },
    {
      id: '9',
      title: 'Fusce non dictum eros',
      content: 'Sed pharetra quam id maximus rhoncus. Morbi at nisi a magna bibendum laoreet eu eget magna. Sed euismod nec tellus eget ultricies. Integer blandit feugiat ligula vitae ultrices.',
      publicationDate: '03.04.2022',
      updateDate: '18.04.2022',
      email: 'user3@gmail.com',
      status: 'closed',
      images: '/images/adsImages/Laptop.jpg',
      prise: 1900,
      phone: '576 794 294',
      location: 'Gdansk',
    },
    {
      id: '10',
      title: 'Ipsum sed ultricies',
      content: 'Nam nisl risus, tristique nec odio vel, pellentesque maximus metus. Nam a purus nec lorem lacinia molestie.',
      publicationDate: '17.02.2022',
      updateDate: '17.02.2022',
      email: 'user2@gmail.com',
      status: 'publihed',
      images: '/images/adsImages/bike02.jpg',
      prise: 300,
      phone: '123 321 444',
      location: 'Warsaw',
    },
    {
      id: '11',
      title: 'Sed elementum fringilla lacinia',
      content: 'Sed vestibulum arcu quis magna convallis, sit amet tempor sem tempor. Cras fringilla, lectus sed accumsan imperdiet, diam dui consectetur lectus, id mattis mauris ligula pulvinar libero.',
      publicationDate: '21.05.2022',
      updateDate: '21.05.2022',
      email: 'user@gmail.com',
      status: 'draft',
      images: '/images/adsImages/car02.jpg',
      prise: 16800,
      phone: '321 321 333',
      location: 'Cracow',
    },
    {
      id: '12',
      title: 'Interdum et malesuada',
      content: 'Pellentesque a molestie nisi. Aenean fermentum justo in elit sodales feugiat. Maecenas egestas ex quis dignissim rhoncus. Mauris ac varius nibh, ut suscipit lorem. Donec eu ante ligula. Suspendisse non quam sed metus blandit fringilla vitae eget urna. Suspendisse molestie eu ante a pharetra.',
      publicationDate: '19.03.2022',
      updateDate: '25.03.2022',
      email: 'user@gmail.com',
      status: 'published',
    },
    {
      id: '13',
      title: 'Sed elementum fringilla lacinia',
      content: 'Sed vestibulum arcu quis magna convallis, sit amet tempor sem tempor. Cras fringilla, lectus sed accumsan imperdiet, diam dui consectetur lectus, id mattis mauris ligula pulvinar libero.',
      publicationDate: '21.05.2022',
      updateDate: '21.05.2022',
      email: 'user@gmail.com',
      status: 'draft',
      images: '/images/adsImages/dog.jpg',
      phone: '321 321 333',
      location: 'Cracow',
    },
    {
      id: '14',
      title: 'Interdum et malesuada',
      content: 'Pellentesque a molestie nisi. Aenean fermentum justo in elit sodales feugiat. Maecenas egestas ex quis dignissim rhoncus. Mauris ac varius nibh, ut suscipit lorem. Donec eu ante ligula. Suspendisse non quam sed metus blandit fringilla vitae eget urna. Suspendisse molestie eu ante a pharetra.',
      publicationDate: '19.03.2022',
      updateDate: '25.03.2022',
      email: 'user@gmail.com',
      status: 'published',
    },
    {
      id: '15',
      title: 'Fusce hendrerit ornare',
      content: 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin sit amet ex et lectus vulputate facilisis sed non neque.',
      publicationDate: '13.02.2022',
      updateDate: '16.03.2022',
      email: 'user1@gmail.com',
      status: 'draft',
      phone: '111 222 333',
      location: 'Cracow',
    },

  ],
  user: {
    status: 'unlogged',
    email: 'user@gmail.com',
  },
};

export default initialState;
